#' Differential Expression Analysis using DESeq2
#' 
#' This script performs DE analysis on Salmon (TPM/counts) or TRC data.
#' It follows the HECATOS project structure and experimental design.
#'
#' Inputs:
#' - Salmon/TRC count data (paths defined in config.R)
#' - BiomaRt for transcript-gene mapping
#'
#' Outputs:
#' - Normalized counts
#' - DE results (TSV)
#' - PCA and Heatmap plots

if (file.exists("utils.R")) { source("utils.R") } else if (file.exists("../utils.R")) { source("../utils.R") }
forceLibrary(c('biomaRt', "tximport", "dplyr", "DESeq2", "grid", "ggplot2", 
               "pheatmap", "BiocParallel"))

# Configuration and Parameters
project_name <- 'Salmon_counts' # Options: 'Salmon_counts', 'TRC_counts'
setSizeFactorToOne <- FALSE 
filtering <- TRUE

# Use multicore if available
if (requireNamespace("BiocParallel", quietly = TRUE)) {
  register(MulticoreParam(workers = 4))
}

##### Data Loading #####

#' Get counts for the specified project
getCts <- function(project_type) {
  if (grepl('TRC', project_type)) {
    # TRC Data logic
    if (dir.exists(TRC_COUNTS_PATH)) {
      setwd(TRC_COUNTS_PATH)
      # Looking for the specific counts file generated by trcToCounts.R
      counts_file = list.files(pattern = 'counts_TRC_UNTR_.*\.tsv')
      if (length(counts_file) > 0) {
        quant_file = read.table(counts_file[1], header = TRUE)
        return(column_to_rownames(quant_file, 'ensembl_gene_id'))
      }
    }
    
    # Fallback to merging TRCscore files if counts file not found
    if (dir.exists(TRC_OUTPUT_PATH)) {
      # This part usually requires finding the latest timestamped directory
      latest_dir = list.dirs(TRC_OUTPUT_PATH, recursive = FALSE) %>% tail(1)
      if (length(latest_dir) > 0) {
        setwd(latest_dir)
        quant_file = mergeFiles(files_patt = 'TRCscore', row_names = TRUE, all = TRUE)
      } else {
        stop("TRC output directory empty or not found.")
      }
    }
    col_quant = 'TRC_'
    transcript_id = 'ensembl_transcript_id'
    
  } else if (grepl('Salmon', project_type)) {
    # Salmon Data logic
    if (dir.exists(SALMON_INPUT_PATH)) {
      setwd(SALMON_INPUT_PATH)
      col_quant = if (grepl('counts', project_type)) 'NumReads' else 'TPM'
      quant_file = mergeFiles(files_patt = 'quant.sf', by_col = 'Name', all = TRUE)
      transcript_id = 'ensembl_transcript_id_version'
    } else {
      stop("Salmon input path not found: ", SALMON_INPUT_PATH)
    }
  } else {
    stop("Unknown project type: ", project_type)
  }

  # Map transcripts to genes and aggregate
  quant_file = quant_file %>% filter(grepl(quant_file[, 1], pattern = 'ENST'))
  mart = openMart2018()
  
  tx2gene = getBM(attributes = c(transcript_id, 'ensembl_gene_id', 'transcript_biotype'), 
                  filters = transcript_id, values = quant_file[, 1], mart = mart)
  
  # Filter for protein coding
  tx2gene = tx2gene[tx2gene$transcript_biotype == 'protein_coding', ]
  
  quant_file_genes = merge(quant_file, tx2gene, by.x = colnames(quant_file)[1], by.y = transcript_id)
  
  cts_data = quant_file_genes %>% dplyr::select(contains(col_quant))
  cts_data = apply(cts_data, 2, round) %>% as.data.frame()
  
  # Aggregate by gene
  cts_final = aggregate(cts_data, by = list(ensembl_gene_id = quant_file_genes$ensembl_gene_id), FUN = sum) %>%
    tibble::column_to_rownames('ensembl_gene_id')
    
  return(cts_final)
}

# Run count retrieval (In a real run, this would be uncommented)
# cts <- getCts(project_name)

# If data files are missing, we provide a warning and stop for now
if (!exists("cts")) {
    warning("Counts data not loaded. Check paths in config.R and availability of data.")
    # For the sake of the pipeline demonstration, we stop here if no data
    # stop("Analysis cannot proceed without data.")
    # Creating a dummy cts if we were just testing structure, but here we expect real data.
}

##### Metadata #####

if (exists("cts")) {
  timepoints_vec <- rep(DEFAULT_TIMEPOINTS, each = 3)
  coldata <- data.frame(row.names = colnames(cts), 
                        timepoints = as.factor(timepoints_vec))

  ##### DESeq2 Pipeline #####

  dds <- DESeqDataSetFromMatrix(countData = cts, 
                                colData = coldata, 
                                design = ~ timepoints)

  if (setSizeFactorToOne) {
    sizeFactors(dds) <- rep(1, ncol(dds))
  }

  dds <- DESeq(dds)

  # Results and Normalization
  norm_data <- counts(dds, normalized = TRUE)
  
  output_dir <- file.path('results', DEFAULT_COMP, 'DESeq2', project_name)
  setOrCreatewd(output_dir)
  
  write.table(norm_data, file = "normalized_counts.txt", sep = "\t", quote = FALSE)

  # PCA Plot
  rld <- vst(dds)
  pca_plot <- plotPCA(rld, intgroup = "timepoints")
  ggsave("pca_plot.png", plot = pca_plot)

  # Extract DEGs for all timepoints vs baseline (002)
  res_names <- resultsNames(dds)[-1]
  all_degs <- data.frame(ensembl_gene_id = rownames(dds))
  
  for (name in res_names) {
    res <- results(dds, name = name)
    res_df <- as.data.frame(res) %>% tibble::rownames_to_column('ensembl_gene_id')
    colnames(res_df)[-1] <- paste(colnames(res_df)[-1], name, sep = "_")
    all_degs <- merge(all_degs, res_df[, c("ensembl_gene_id", paste0("padj_", name))], by = "ensembl_gene_id", all = TRUE)
    
    # Save individual result
    write.table(res, file = paste0("DE_results_", name, ".txt"), sep = "\t", quote = FALSE)
  }
  
  write.table(all_degs, file = "summary_DEGs_padj.txt", sep = "\t", quote = FALSE, row.names = FALSE)
  
  print("DESeq2 Analysis completed successfully.")
}